// Copyright unrealSTS. All Rights Reserved.
//
// Native GameplayTag 声明：与 Plugins/STSFramework/Config/Tags/STSGameplayTags.ini 保持同步。
// 用法：STSGameplayTags::Card_Type_Attack

#pragma once

#include "NativeGameplayTags.h"

namespace STSGameplayTags
{
	// STS.Card.Type.*
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Card_Type_Attack);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Card_Type_Skill);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Card_Type_Power);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Card_Type_Status);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Card_Type_Curse);

	// STS.Card.Rarity.*
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Card_Rarity_Basic);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Card_Rarity_Common);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Card_Rarity_Uncommon);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Card_Rarity_Rare);

	// STS.Card.Pool.*
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Card_Pool_Ironclad);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Card_Pool_Colorless);

	// STS.Card.State.*
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Card_State_Upgraded);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Card_State_CombatUpgrade);

	// STS.Card.Keyword.*
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Card_Keyword_Exhaust);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Card_Keyword_Ethereal);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Card_Keyword_Retain);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Card_Keyword_Unplayable);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Card_Keyword_Innate);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Card_Keyword_XCost);

	// STS.Status.*
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Vulnerable);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Weak);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Poison);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Strength);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Artifact);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Barricade);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Decay_OnTurnEnd);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Decay_OnTurnStart);

	// STS.Phase.*
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Phase_PlayerTurn);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Phase_EnemyTurn);

	// STS.Event.*
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_Start);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_Victory);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_Defeat);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Turn_PlayerStart);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Turn_PlayerEnd);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Turn_EnemyStart);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Turn_EnemyEnd);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Card_Played);

	// STS.Relic.Trigger.*
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Relic_Trigger_CombatStart);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Relic_Trigger_CombatVictory);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Relic_Trigger_PlayerTurnStart);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Relic_Trigger_PlayerTurnEnd);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Relic_Trigger_OnCardPlayed);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Relic_Trigger_OnDamageReceived);

	// STS.Action.*
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_PlayCard);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_EnemyAct);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_RelicListen);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_StatusTurn);

	// STS.Data.*
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Heal);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Block);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Cost);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Stacks);

	// STS.Granted.*
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Granted_Power);

	// STS.UI.Layer.*
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Game);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_GameMenu);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Menu);
	STSFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Modal);
}
